#!/usr/bin/env node

const _404 = require('./src')

let config = {
  folder : process.argv[2] || '.' ,
  ignore: String(process.argv[3]).split(','),
  log: console.log
}
let links = _404(config)

links.on('end', (result) => {
  console.log('=====================================================')
  if (result.length) {
    result.forEach(err => {
      config.log(err.message)
    })
  } else {
    config.log('All links are OK')
  }
  
  process.exit(result.length ? 1 : 0)
})
